import React, { useState } from 'react';

const FilterData = [
  {
    id: 4,
    company: 'Two Sigma',
    userid: 3,
    location: 'New York,New York',
    jobdescription: 'principal engineer',
    salaryrange: '500,000-999,000',
    jobstatus: 'final round',
    //   interviewdate: 2022-05-04T04:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 19,
    company: '',
    userid: 3,
    location: '',
    jobdescription: '',
    salaryrange: '',
    jobstatus: '',
    //   interviewdate: 2022-04-24T04:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 20,
    company: '',
    userid: 3,
    location: '',
    jobdescription: '',
    salaryrange: '',
    jobstatus: '',
    //   interviewdate: 2023-02-06T05:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 23,
    company: '',
    userid: 3,
    location: '',
    jobdescription: '',
    salaryrange: '',
    jobstatus: '',
    //   interviewdate: 2022-04-06T04:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 26,
    company: 'Google',
    userid: 3,
    location: 'Here',
    jobdescription: 'Senior lead',
    salaryrange: '300000',
    jobstatus: 'recruitercall',
    //   interviewdate: 2022-04-06T04:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 28,
    company: 'Capital One',
    userid: 3,
    location: 'NY',
    jobdescription: 'Senior developer',
    salaryrange: '300000',
    jobstatus: 'wishlist',
    //   interviewdate: 2022-04-06T04:00:00.000Z,
    hiredstatus: false,
  },
  {
    id: 29,
    company: 'Google',
    userid: 3,
    location: 'NY',
    jobdescription: 'Senior lead',
    salaryrange: '300000',
    jobstatus: '',
    //   interviewdate: 2022-04-15T04:00:00.000Z,
    hiredstatus: false,
  },
];

export default FilterData;
